version: 2

updates:
  # To keep Terraform modules up to date
  - package-ecosystem: "terraform"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    assignees:
      - "zahorniak"

  # To keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - "zahorniak"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
